*****************************************************************************
*     fmodules.inc: include file for fortran modules
*****************************************************************************

      INTEGER*4 MAXREACH,MAXPRINT,MAXBOUND,MAXSEG,MAXSOLUTE,MAXFLOWLOC

      PARAMETER (MAXREACH = 30)
      PARAMETER (MAXPRINT = 30)
      PARAMETER (MAXBOUND = 200)
      PARAMETER (MAXSEG = 5000)
      PARAMETER (MAXSOLUTE = 3)
      PARAMETER (MAXFLOWLOC = 30)

